server:
  port: 8080

spring:
  application:
    name: auth-api
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: com.x.data.core.hibernate.dialect.ExtendedH2Dialect
      format_sql: true
    show-sql: true

jwt:
  secret: javainuse
  jwtExpirationInMs: 18000000
