server:
  port: 8081
  servlet:
    context-path: /security-service

spring:
  application:
    name: security-service
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: com.x.data.core.hibernate.dialect.ExtendedH2Dialect
      format_sql: true
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

jwt:
  secret: javainuse
  jwtExpirationInMs: 18000000
